### ISSUE TITLE
Animation for the word community is a bit much

### ISSUE THREAD

**Issue by digitalman2112** [MakerFaireOrlando/brightbikes.org#3]
Its fun, but distracting (and it took me a minute of moving my mouse to understand what was happening) - would prefer we not use it.

![image](https://user-images.githubusercontent.com/452840/118553538-71c44980-b72e-11eb-969c-8819f20ebffb.png)

**Comment by CazsSo** [comment]
Fixed in latest PR. Changed to neon text.

**Comment by digitalman2112** [comment]
Love it!
