### ISSUE TITLE
Need new "about" text

### ISSUE THREAD

**Issue by digitalman2112** [MakerFaireOrlando/brightbikes.org#5]
![image](https://user-images.githubusercontent.com/452840/118553810-cebfff80-b72e-11eb-9825-be8b6639b527.png)

We are building a fleet of art bikes with more than 1,600 LEDs each! These bikes will display patterns created by local interactive artists and you’ll see the bikes popping up at lots of iconic Orlando locations in the coming months. Send us a note to get involved!

**Comment by CazsSo** [comment]
Updated in Latest PR.
